app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Items
    url(r'^items/$', views.item_page, name='list_items'),
    url(r'^items/delete/(?P<item_id>[0-9]+)/$', views.delete_item, name='delete_item'),
    url(r'^items/update/(?P<item_id>[0-9]+)/$', views.update_item, name='update_item'),

    # Categories
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^categories/update/(?P<category_id>[0-9]+)/$', views.update_category, name='update_category'),
    url(r'^categories/delete/(?P<category_id>[0-9]+)/$', views.delete_category, name='delete_category'),

    # Inventory
    url(r'^inventory/process_item/(?P<item_id>[0-9]+)/$', views.process_item, name='process_item'),
    url(r'^inventory/view/$', views.view_inventory, name='view_inventory'),
    url(r'^inventory/update/(?P<itemloc_id>[0-9]+)/$', views.update_inventory, name='update_inventory'),
    url(r'^inventory/delete/(?P<itemloc_id>[0-9]+)/$', views.delete_inventory, name='delete_inventory'),

    # Locations
    url(r'^locations/$', views.location_page, name='location_list'),
    url(r'^locations/delete/(?P<loc_id>[0-9]+)/$', views.delete_location, name='delete_location'),
    url(r'^locations/update/(?P<loc_id>[0-9]+)/$', views.update_location, name='update_location'),


    url(r'^process_items/$', views.processitems_list, name='process_items'),
    url(r'^process_items/create_recipe/(?P<item_id>[0-9]+)/$', views.create_recipe, name='create_recipe'),
    url(r'^process_items/update_recipe/(?P<item_id>[0-9]+)/$', views.update_recipe, name='update_recipe'),
    url(r'^process_items/process/(?P<item_id>[0-9]+)/$', views.process_item, name='process'),
    url(r'^process_items/delete_ingredient/(?P<item_id>[0-9]+)/$', views.delete_ingredient, name='delete_ingredient'),

    # Suppliers
    url(r'^suppliers/$', views.suppliers, name='suppliers'),
    url(r'^suppliers/update/(?P<supplier_id>[0-9]+)/$', views.update_supplier, name='update_supplier'),
    url(r'^suppliers/delete/(?P<supplier_id>[0-9]+)/$', views.delete_supplier, name='delete_supplier'),

    # Checklists
    url(r'^checklist/$', views.checklist_page, name='checklist'),
    url(r'^checklist/add$', views.add_checklist, name='add_checklist'),
    url(r'^checklist/(?P<check_id>[0-9]+)/$', views.specific_checklist, name='specific_checklist'),
    url(r'^checklist/delete/(?P<check_id>[0-9]+)/$$', views.delete_checklist, name='delete_checklist'),
    url(r'^checklist/update/(?P<check_id>[0-9]+)/$$', views.update_checklist, name='update_checklist'),
    url(r'^checklist/item/delete/(?P<item_id>[0-9]+)/$$', views.delete_check, name='delete_check'),

    url(r'^arrival/$', views.arrival_list, name='arrivals'),
    url(r'^arrival/add$', views.add_arrival, name='add_arrival'),
    url(r'^arrival/(?P<arrival_id>[0-9]+)/$', views.specific_arrivalItems, name='arrivalItems'),
    url(r'^arrival/delete/(?P<arrival_id>[0-9]+)/$', views.delete_arrival, name='delete_arrival'),
    url(r'^arrival/update/(?P<arrival_id>[0-9]+)/$', views.update_arrival, name='update_arrival'),

    url(r'^transfer/$', views.create_transfer, name='create_transfer'),
    # url(r'^arrival/payable/(?P<arrival_id>[0-9]+)/$', views.payable_arrival_pdf, name='payable_arrival_pdf'),
    url(r'^arrival/receipt/(?P<arrival_id>[0-9]+)/$', views.receipt_arrival_pdf, name='receipt_arrival_pdf'),
    url(r'^arrival/download/(?P<arrival_id>[0-9]+)/$', views.download_receipt_arrival, name='download_receipt_arrival'),

    # Employees
    url(r'^employees/$', views.employees_list, name='employees_list'),
    url(r'^employees/delete/(?P<employee_id>[0-9]+)/$$', views.delete_employee, name='delete_employee'),
    url(r'^employees/update/(?P<employee_id>[0-9]+)/$$', views.update_employee, name='update_employee'),
    url(r'^employees/create_account/(?P<employee_id>[0-9]+)/$$', views.create_account, name='create_account'),

    #Reports
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^reports/create/(?P<check_id>[0-9]+)/$', views.create_report, name='create_report'),
    url(r'^reports/update/(?P<report_id>[0-9]+)/$', views.update_report, name='update_report'),
    url(r'^reports/create_report/(?P<report_id>[0-9]+)/$', views.daily_report_pdf, name='daily_report'),
    url(r'^reports/create_report_download/(?P<report_id>[0-9]+)/$', views.daily_report_pdf_download, name='daily_report_download'),

    url(r'^expenses/$', views.all_expenses, name='expenses'),

    #Transfer
    url(r'^transfers/$', views.transfer_list, name='transfers'),
    url(r'^transfers/(?P<transfer_id>[0-9]+)$', views.specific_transferItems, name='specific_transfer'),
    url(r'^transfers/receipt/(?P<transfer_id>[0-9]+)$', views.transfer_receipt_pdf, name='transfer_receipt'),
    url(r'^transfers/download/(?P<transfer_id>[0-9]+)$', views.transfer_download_pdf, name='transfer_download'),

    #Branch Items
    url(r'^branch_items/$', views.branch_items, name='branch_items'),
    url(r'^branch_items/inventory/(?P<branch_id>[0-9]+)$$', views.branch_inventory, name='branch_inventory'),

    #Permission
    url(r'^permission/send_arrival/$', views.permission_update_arrival, name='permission_arrival'),
    url(r'^permission/send_report/$', views.permission_update_report, name='permission_report'),
    url(r'^permission/approve/(?P<user_id>[0-9]+)/(?P<request_id>[0-9]+)$$', views.approve_permission, name='approve'),

    url(r'^permissions/$', views.permissions, name='permissions'),

    # Users
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'', views.index, name='index'),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls'))
]

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import connection, models


class MyManager(models.Manager):
    def raw_as_qs(self, raw_query, params=()):
        """Execute a raw query and return a QuerySet.  The first column in the
        result set must be the id field for the model.
        :type raw_query: str | unicode
        :type params: tuple[T] | dict[str | unicode, T]
        :rtype: django.db.models.query.QuerySet
        """
        cursor = connection.cursor()
        try:
            cursor.execute(raw_query, params)
            return self.filter(id__in=(x[0] for x in cursor))
        finally:
            cursor.close()


class BasicModels(models.Model):
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AccountManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        if not username:
            raise ValueError("Users must have a valid username!")

        account = self.model(
            username=username,
            firstname=kwargs.get('firstname', None),
            middle_initial=kwargs.get('middle_initial', None),
            lastname=kwargs.get('lastname', None),
            gender=kwargs.get('gender', None),
            position=kwargs.get('position', None),
            is_staff=kwargs.get('is_staff', True),
        )
        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, username, password=None, **kwargs):
        account = self.create_user(username, password, **kwargs)
        account.is_admin= True
        account.can_encode=True
        account.can_print=True
        account.can_update_arrival=True
        account.can_update_report=True
        account.save()
        return account


class UserAccount(AbstractBaseUser):
    username = models.CharField(unique=True, max_length=50)

    is_staff = models.BooleanField(default=False)
    can_print = models.BooleanField(default=False)
    can_encode = models.BooleanField(default=False)
    can_update_arrival = models.BooleanField(default=False)
    can_update_report = models.BooleanField(default=False)

    firstname = models.CharField(max_length=200, blank=True, null=True)
    middle_initial = models.CharField(max_length=2, blank=True, null=True)
    lastname = models.CharField(max_length=200, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    position = models.CharField(max_length=200, blank=True, null=True)

    is_admin = models.BooleanField(default=False)

    objects = AccountManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['firstname', 'lastname']

    def get_full_name(self):
        return (self.firstname + " " + self.lastname)

    def get_short_name(self):
        return self.username

    @property
    def is_superuser(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def __unicode__(self):
        return self.username


class Employee(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    position = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    has_account = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Categories(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)

    def __str__(self):
        return self.name

class Item(BasicModels):
    objects = MyManager()
    types = (
        ('raw', 'raw'),
        ('processed', 'processed'),
        ('process&raw', 'process&raw'),
    )
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    price = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15)
    type = models.CharField(max_length=10, choices=types, default='raw')
    category = models.ForeignKey(Categories)
    has_recipe = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering=['name']


class Location(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    address = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class ItemLocation(models.Model):
    item = models.ForeignKey(Item)
    location = models.ForeignKey(Location)
    current_stock = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.item.name


class Supplier(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Transfer(BasicModels):
    From = models.ForeignKey(Location, related_name="from+")
    To = models.ForeignKey(Location, related_name="to+")
    items = models.ManyToManyField(Item, through="ItemTransfer")
    user = models.ForeignKey(UserAccount)


class ItemTransfer(BasicModels):
    quantity = models.IntegerField(default=0)
    item = models.ForeignKey(Item)
    transfer = models.ForeignKey(Transfer, null=True, blank=True)

    @property
    def calculate_total(self):
        return self.item.price * self.quantity


class Arrival(BasicModels):
    types = (
        ('cash', 'cash'),
        ('payable', 'payable'),
    )
    type = models.CharField(max_length=10, choices=types, default='cash')
    items = models.ManyToManyField(Item, through='ItemArrival')
    supplier = models.ForeignKey(Supplier)
    location = models.ForeignKey(Location)
    receipt_no = models.IntegerField()
    user = models.ForeignKey(UserAccount)

    class Meta:
        ordering = ['-created_date']

    def __unicode__(self):
        return self.id

    def items_list(self):
        return [a.item for a in self.items.all()]


    @staticmethod
    def apply_filter(start, end, supplier):
        items = Arrival.objects.filter(supplier=supplier).filter(created_date__gt=start, created_date__lt=end)
        return items

    @property
    def get_grand_total(self):
        grand_total = 0
        items_set = self.items.all()
        for item in items_set:
            grand_total = grand_total + item.calculate_total
        return grand_total



class ItemArrival(BasicModels):
    item = models.ForeignKey(Item)
    arrival = models.ForeignKey(Arrival)
    quantity = models.IntegerField()

    def __unicode__(self):
        return " ".join((unicode(self.item.name), unicode(self.quantity)))

    @property
    def calculate_total(self):
        return self.item.price * self.quantity


class Checklist(BasicModels):
    name = models.CharField(max_length=255)
    items = models.ManyToManyField(Item, through='ChecklistField')


class ChecklistField(BasicModels):
    item = models.ForeignKey(Item, null=True, blank=True)
    display_order = models.IntegerField()
    checklist = models.ForeignKey(Checklist, null=True, blank=True)

    class Meta:
        ordering=['display_order']


class Recipe(BasicModels):
    item = models.ForeignKey(Item, related_name='item+')
    ingredient = models.ManyToManyField(Item, through='Ingredients')


class Ingredients(BasicModels):
    item = models.ForeignKey(Item)
    processed_item = models.ForeignKey(Recipe, null=True, blank=True)

class Process(BasicModels):
    location = models.ForeignKey(Location)
    item = models.ForeignKey(Item, related_name='item+')
    quantity_yield = models.IntegerField()
    ingredient = models.ManyToManyField(Item, through='ItemIngredient')

class ItemIngredient(BasicModels):
    item = models.ForeignKey(Item)
    quantity = models.IntegerField()
    process = models.ForeignKey(Process, null=True, blank=True)


class Report(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    location = models.ForeignKey(Location)
    user = models.ForeignKey(UserAccount, null=True, blank=True)
    items = models.ManyToManyField(Item, through='ItemExpense')

class Expenses(BasicModels):
    expenses = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15, default=0)
    amount=models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15, default=0)
    report = models.ForeignKey(Report, null=True, blank=True)

class ItemExpense(BasicModels):
    item= models.ForeignKey(Item)
    new = models.IntegerField()
    beg = models.IntegerField()
    total= models.IntegerField()
    end= models.IntegerField()
    report = models.ForeignKey(Report, null=True, blank=True)

class Permission(BasicModels):
    user= models.ForeignKey(UserAccount)
    message=models.TextField()
    requested_report = models.BooleanField(default=False)
    requested_arrival = models.BooleanField(default=False)

app/templates/app/add_arrival.html
 {% extends "app/base.html" %}
{% load staticfiles %}


{% block content %}
<style type="text/css">
    .add-row {
        margin-top: 10px;
        width: 150px;
    }

    .delete-row {
        width: 80%;
        margin-left: 10%;
    }
    #id_transfer th {
        padding: 10px;
        text-align: center;
    }
    #id_transfer td {
        padding: 10px;
        text-align: center;

    }
</style>

<div class="row">
    <div class="col-md-7 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading" >ADD ARRIVAL</div>
                <div class="panel-body">
                    <form class="form" method="POST">
                        {% csrf_token %}
                        <ul class="list-inline">
                        {% for field in ArrivalForm %}
                       <li style="margin-left: 15px"> {{field.label_tag}} {{field}}</li>
                         {% endfor %}
                         </ul>

                            <div class="panel-body">
                        <table id="id_transfer" width="100%" border="0" cellpadding="50" cellspacing="1500">
                            <thead>
                                <tr>
                                    <th scope="col">Item</th>
                                    <th scope="col">Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for form in formset %}
                                <tr id="{{ form.prefix }}-row"  class="dynamic-form">
                                    <td>{{form.item}}</td>
                                    <td>{{form.quantity}}</td>
                                   <td><a id="remove-{{ form.prefix }}-row" href="javascript:void(0)" class="btn btn-danger delete-row"><span class="glyphicon glyphicon-remove"></span></a></td>
                                   <td></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <center><a href="javascript:void(0)" class="btn btn-primary add-row">Add More</a></center>
                        {{ formset.management_form }}
                        <br>
                        <div class="form-group" style="width:150px; float:right">
                            <input type="submit" class="form-control btn btn-success" value="Submit"/>
                        </div>
                        <div><a style="width:150px" class="btn btn-default" href="{% url 'arrivals' %}">Back</a></div>
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/app/add_report.html
{% extends "app/base.html" %}
{% block content %}
	<div class="row">
		<h2 class="text-center">Daily Report<span style="float: right">
        <a class="btn btn-default" href="{% url 'reports' %}">Back</a></span></h2>
		<br>

		<form class="form" method="POST">
		{% if messages %}
		        <ul class="messages">
                    {% for message in messages %}
                   <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
                        {% csrf_token %}
                        <ul class="list-inline">
                        {% for field in ReportForm %}
                       <li style="margin-left: 0px"> {{field.label_tag}} {{field}}</li>
                         {% endfor %}
                         </ul>
                         <br>
		<div class="table-responsive">
			<table class="table table-bordered table-hover">
			<thead>
			  <tr>
				<th>Items</th>
				<th>End</th>
			  </tr>
			</thead>
			<tbody>
			{% for form in formset1 %}
			  <tr>
				<td>{{form.item}}</td>
				<td>{{form.end}}</td>
			  </tr>
			  {% endfor %}
			</tbody>
		</table>
		 {{ formset1.management_form }}
		</div>
             <table id="id_transfer" width="50%" border="0" cellpadding="50" cellspacing="1500">
               <thead>
                  <tr>
                     <th scope="col">Expenses</th>
                     <th scope="col">Amount</th>
                  </tr>
               </thead>
                <tbody>
                 {{ formset2.management_form }}
                   {% for form1 in formset2 %}
                   <br>
                      <tr id="{{form1.prefix}}-row"  class="dynamic-form">
                        <td>{{form1.expenses}}</td>
                        <td>{{form1.amount}}</td>
                        <td><a id="remove-{{ form1.prefix }}-row" href="javascript:void(0)" class="btn btn-danger delete-row"><span class="glyphicon glyphicon-remove"></span></a></td>
                      </tr>
                   {% endfor %}
                </tbody>
             </table>
             <br>
             <br>
                  <center><a href="javascript:void(0)" class="btn btn-primary add-row" style="margin-left: -500px" >Add More</a></center>

                   <br>
		 <div class="form-group" style="width:150px; float:right">
             <input type="submit" class="form-control btn btn-success" value="Submit"/>
         </div>
	</form>
	</div>


{% endblock %}

app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>B-Bu-Q Inventory System</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="css/normalize.css" rel="stylesheet" type="text/css"/>
    <link href="{% static "css/datepicker.css" %}" rel="stylesheet" type="text/css"/>



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">B-Bu-Q Inventory System</a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">
            <li>
                <a href="{% url "logout" %}">Log out</a>
            </li>
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li>
                    <a href="#"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'list_items' %}"><i class="fa fa-fw fa-bar-chart-o"></i> Items</a>
                </li>
                 <li>
                    <a href="{% url 'process_items' %}"><i class="fa fa-fw fa-bar-chart-o"></i> Process Items</a>
                </li>
                <li>
                    <a href="{% url 'view_inventory' %}"><i class="fa fa-fw fa-table"></i> Inventory</a>
                </li>
                 <li>
                    <a href="{% url 'reports' %}"><i class="fa fa-fw fa-file"></i> Sales/Inventory Reports</a>
                </li>
                <li>
                    <a href="{%url 'branch_items' %}"><i class="fa fa-fw fa-table"></i> Branch Items</a>
                </li>
                <li>
                    <a href="{% url 'arrivals' %}"><i class="fa fa-fw fa-truck"></i> Arrival</a>
                </li>
                <li>
                    <a href="{% url 'transfers' %}"><i class="fa fa-fw fa-calendar"></i> Transfers</a>
                </li>
                <li>
                    <a href="{% url 'location_list' %}"><i class="fa fa-fw fa-map-marker"></i> Location</a>
                </li>
                <li>
                    <a href="{% url 'suppliers' %}"><i class="fa fa-fw fa-wrench"></i> Supplier</a>
                </li>
                 {% if request.user.is_active and request.user.is_superuser %}
                <li>
                    <a href="{% url 'employees_list' %}"><i class="fa fa-fw fa-wrench"></i> Employees</a>
                </li>
                <li>
                    <a href="{% url 'permissions' %}"><i class="fa fa-fw fa-calendar"></i> Permission Requests</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'checklist' %}"><i class="fa fa-fw fa-calendar"></i> Checklist</a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>

    <div id="page-wrapper" style="min-height: 700px">

        <div class="container-fluid" style="margin: 0 5%">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</div>

<!-- jQuery -->
<script src="{% static "js/jquery.js" %}"></script>

<script type="text/javascript">
    jQuery.browser = {};
    (function () {
        jQuery.browser.msie = false;
        jQuery.browser.version = 0;
        if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
            jQuery.browser.msie = true;
            jQuery.browser.version = RegExp.$1;
        }
    })();
</script>

<script src="{% static "js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>

<script>

   $(function() {
  var oTable = $('#example').DataTable({
    "oLanguage": {
      "sSearch": "Search  "
    },
    "iDisplayLength": -1,
    "sPaginationType": "full_numbers",

  initComplete: function () {
            this.api().columns('.select-filter').every( function () {
                var column = this.column(3);
                var select = $('<select><option value="">All</option></select>')
                    .appendTo( $(column.header()) )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
  });

  $("#datepicker_from").datepicker({
    buttonImageOnly: false,
    "onSelect": function(date) {
      minDateFilter = new Date(date).getTime();
      oTable.draw();
    }
  }).keyup(function() {
    minDateFilter = new Date(this.value).getTime();
    oTable.draw();
  });

  $("#datepicker_to").datepicker({
    buttonImageOnly: false,
    "onSelect": function(date) {
      maxDateFilter = new Date(date).getTime();
      oTable.draw();
    }
  }).keyup(function() {
    maxDateFilter = new Date(this.value).getTime();
    oTable.draw();
  });

});

// Date range filter
minDateFilter = "";
maxDateFilter = "";

$.fn.dataTableExt.afnFiltering.push(
  function(oSettings, aData, iDataIndex) {
    if (typeof aData._date == 'undefined') {
      aData._date = new Date(aData[0]).getTime();
    }

    if (minDateFilter && !isNaN(minDateFilter)) {
      if (aData._date < minDateFilter) {
        return false;
      }
    }

    if (maxDateFilter && !isNaN(maxDateFilter)) {
      if (aData._date > maxDateFilter) {
        return false;
      }
    }

    return true;

  }
);

</script>

<script src="{% static "js/jquery.formset.js" %}"></script>
<script type="text/javascript">
    <!--
    $(function () {
        $('.add-row').click(function() {
            return addForm(this, 'form');
        });
        $('.delete-row').click(function() {
            return deleteForm(this, 'form');
        })
    })
//-->
</script>

<script type="text/javascript">
    $(function () {
        n =  new Date();
        y = n.getFullYear();
        m = n.getMonth() + 1;
        d = n.getDate();
        document.getElementById("date_i").innerHTML = m + "/" + d + "/" + y;
    })
</script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "bower_components/sweetalert2/dist/sweetalert2.all.min.js" %}"></script>


</body>

</html>

app/templates/app/permissions.html
{% extends "app/base.html" %}

{% block content %}
    <div class="row">
        <h1 class="page-header">Permissions</h1>
    </div>

    <div class="row form-inline">
        <br>
        <br>
        <table id="example" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>User</th>
                <th>Message</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
                {% for p in permissions %}
            <tr>
                <td>{{ p.user }}</td>
                <td>{{ p.message }}</td>
                <td width="40%">
                 <a class="btn btn-info btn-sm" href="{% url 'approve' p.user.id p.id %}">Approve</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}